import type { Report } from "./reports.js";

type Lang = "en" | "tr";

const L = {
  en: {
    title: "Cortex report",
    period: "Period",
    days: "days",
    atAGlance: "At a glance",
    activity: "Activity",
    byAi: "by AI",
    byHumans: "by humans",
    aiChanges: "Changes logged by AI",
    withoutWhy: "without a reason",
    created: "Items created",
    closed: "Items closed",
    questions: "Questions",
    asked: "asked",
    answered: "answered",
    medianAnswer: "median answer time",
    hoursShort: "h",
    decisions: "Decisions",
    proposed: "proposed",
    accepted: "accepted",
    rejected: "rejected",
    approvals: "AI drafts",
    approved: "approved",
    pending: "pending",
    oldest: "oldest",
    knowledge: "Knowledge health",
    nodes: "nodes",
    linked: "linked to code",
    stale: "stale",
    undocumented: "undocumented",
    updated: "updated this period",
    noGit: "not a git repository: staleness unavailable",
    whatAiDid: "What the AI did, and why",
    decisionsMade: "Decisions",
    closedIssues: "Closed issues",
    openFor: "open for",
    daysShort: "d",
    waiting: "Waiting on people",
    blocking: "Blocking questions",
    pendingApprovals: "Drafts waiting for approval",
    staleNodes: "Knowledge that may be out of date",
    undocumentedBranches: "Undocumented branches",
    issueAging: "Open issues by age",
    actors: "By actor",
    actor: "Actor",
    kind: "Kind",
    logged: "Logged",
    writes: "Other writes",
    draftsCol: "Drafts approved / rejected",
    approvalRate: "Approval rate",
    nothing: "Nothing.",
    footer: "Generated by Cortex from the project's files and activity log. No AI was used to write this report.",
  },
  tr: {
    title: "Cortex raporu",
    period: "Dönem",
    days: "gün",
    atAGlance: "Özet",
    activity: "Aktivite",
    byAi: "AI",
    byHumans: "insan",
    aiChanges: "AI'ın kaydettiği değişiklikler",
    withoutWhy: "gerekçesiz",
    created: "Açılan kayıtlar",
    closed: "Kapanan kayıtlar",
    questions: "Sorular",
    asked: "soruldu",
    answered: "cevaplandı",
    medianAnswer: "ortanca cevap süresi",
    hoursShort: "sa",
    decisions: "Kararlar",
    proposed: "önerildi",
    accepted: "kabul",
    rejected: "ret",
    approvals: "AI taslakları",
    approved: "onaylandı",
    pending: "bekliyor",
    oldest: "en eskisi",
    knowledge: "Bilgi sağlığı",
    nodes: "düğüm",
    linked: "koda bağlı",
    stale: "eskimiş",
    undocumented: "belgelenmemiş",
    updated: "bu dönem güncellendi",
    noGit: "git deposu değil: eskime tespiti yok",
    whatAiDid: "AI ne yaptı, neden yaptı",
    decisionsMade: "Kararlar",
    closedIssues: "Kapanan issue'lar",
    openFor: "açık kaldı",
    daysShort: "g",
    waiting: "İnsanları bekleyenler",
    blocking: "Engelleyici sorular",
    pendingApprovals: "Onay bekleyen taslaklar",
    staleNodes: "Eskimiş olabilecek bilgi",
    undocumentedBranches: "Belgelenmemiş dallar",
    issueAging: "Açık issue'ların yaşı",
    actors: "Aktörlere göre",
    actor: "Aktör",
    kind: "Tür",
    logged: "Kayıt",
    writes: "Diğer yazımlar",
    draftsCol: "Taslak onay / ret",
    approvalRate: "Onay oranı",
    nothing: "Yok.",
    footer: "Cortex tarafından projenin dosyalarından ve aktivite günlüğünden üretildi. Bu raporu yazmak için AI kullanılmadı.",
  },
} satisfies Record<Lang, Record<string, string>>;

// Markdown is for people: paste it into Slack, a PR or a wiki. Table cells are escaped; nothing is truncated silently.
export function reportToMarkdown(r: Report, lang: Lang = "en"): string {
  const t = L[lang];
  const esc = (s: string) => s.replace(/\|/g, "\\|").replace(/\r?\n/g, " ");
  const day = (iso: string) => iso.slice(0, 10);
  const pct = (x: number | null) => (x === null ? "—" : `${Math.round(x * 100)}%`);
  const list = (rows: string[]) => (rows.length ? rows.map((x) => `- ${x}`).join("\n") : `_${t.nothing}_`);
  const T = r.totals;
  const k = r.knowledge;

  const out: string[] = [];
  out.push(`# ${t.title}`, "", `**${t.period}:** ${day(r.period.since)} → ${day(r.period.until)} (${r.period.days} ${t.days})`, "");

  out.push(`## ${t.atAGlance}`, "");
  out.push(`| | |`, `|---|---|`);
  out.push(`| ${t.activity} | ${T.activity.total} (${t.byAi} ${T.activity.ai} · ${t.byHumans} ${T.activity.human}) |`);
  out.push(`| ${t.aiChanges} | ${T.ai_logged_changes}${T.ai_changes_without_why ? ` (${T.ai_changes_without_why} ${t.withoutWhy})` : ""} |`);
  out.push(`| ${t.created} | ${T.items_created.total}${fmtTypes(T.items_created.by_type)} |`);
  out.push(`| ${t.closed} | ${T.items_closed.total}${fmtTypes(T.items_closed.by_type)} |`);
  out.push(
    `| ${t.questions} | ${T.questions.asked} ${t.asked} · ${T.questions.answered} ${t.answered}${T.questions.median_answer_hours !== null ? ` · ${t.medianAnswer} ${T.questions.median_answer_hours} ${t.hoursShort}` : ""} |`,
  );
  out.push(`| ${t.decisions} | ${T.decisions.proposed} ${t.proposed} · ${T.decisions.accepted} ${t.accepted} · ${T.decisions.rejected} ${t.rejected} |`);
  out.push(
    `| ${t.approvals} | ${T.approvals.approved} ${t.approved} · ${T.approvals.rejected} ${t.rejected} · ${T.approvals.pending} ${t.pending}${T.approvals.oldest_pending_days !== null ? ` (${t.oldest} ${T.approvals.oldest_pending_days} ${t.daysShort})` : ""} |`,
  );
  out.push(
    `| ${t.knowledge} | ${k.nodes} ${t.nodes} · ${k.with_code_links} ${t.linked} · ${k.git ? `${k.stale} ${t.stale} (${pct(k.stale_ratio)})` : t.noGit} · ${k.undocumented} ${t.undocumented} · ${k.updated_in_period} ${t.updated} |`,
  );
  out.push("");

  out.push(`## ${t.whatAiDid}`, "");
  out.push(
    list(
      r.highlights.ai_changes.map(
        (c) => `**${esc(c.summary)}** — ${c.actor}, ${day(c.at)}${c.why ? `\n  - _${esc(c.why)}_` : ""}${c.files?.length ? `\n  - \`${c.files.map(esc).join("`, `")}\`` : ""}`,
      ),
    ),
    "",
  );

  out.push(`## ${t.decisionsMade}`, "", list(r.highlights.decisions.map((d) => `${esc(d.title)} — **${d.status}** (${d.by}, ${day(d.at)})`)), "");
  out.push(
    `## ${t.closedIssues}`,
    "",
    list(r.highlights.closed_issues.map((i) => `${esc(i.title)}${i.resolution ? ` — ${i.resolution}` : ""} (${t.openFor} ${i.days_open} ${t.daysShort})`)),
    "",
  );

  out.push(`## ${t.waiting}`, "");
  out.push(`### ${t.blocking}`, "", list(r.attention.blocking_questions.map((q) => `${esc(q.title)} — ${q.asked_by} → ${q.assignee ?? "—"} (${q.age_days} ${t.daysShort})`)), "");
  out.push(`### ${t.pendingApprovals}`, "", list(r.attention.pending_approvals.map((d) => `${esc(d.title)} (${d.kind}) — ${d.proposed_by}, ${d.age_days} ${t.daysShort}`)), "");
  out.push(`### ${t.issueAging}`, "", `| | ${r.attention.issue_aging.map((b) => b.bucket).join(" | ")} |`, `|---|${r.attention.issue_aging.map(() => "---:").join("|")}|`);
  out.push(`| ${r.attention.open_issues} | ${r.attention.issue_aging.map((b) => b.count).join(" | ")} |`, "");
  out.push(`### ${t.staleNodes}`, "", list(r.attention.stale_nodes.map((s) => `\`${s.path}\` ← ${s.files.map((f) => `\`${esc(f)}\``).join(", ")}`)), "");
  out.push(`### ${t.undocumentedBranches}`, "", list(r.attention.undocumented.map((p) => `\`${p}\``)), "");

  out.push(`## ${t.actors}`, "", `| ${t.actor} | ${t.kind} | ${t.logged} | ${t.writes} | ${t.draftsCol} | ${t.approvalRate} |`, "|---|---|---:|---:|---:|---:|");
  for (const a of r.actors) out.push(`| ${a.id} | ${a.kind} | ${a.logged} | ${a.writes} | ${a.drafts.approved} / ${a.drafts.rejected} | ${pct(a.approval_rate)} |`);
  out.push("", `_${t.footer}_`, "");
  return out.join("\n");
}

function fmtTypes(by: Record<string, number>): string {
  const parts = Object.entries(by).map(([k, v]) => `${k} ${v}`);
  return parts.length ? ` (${parts.join(", ")})` : "";
}
